# Generated by Django 3.2.4 on 2021-06-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20210622_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaire'},
        ),
    ]
