# Generated by Django 3.2.4 on 2021-06-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='choice4',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.category'),
        ),
    ]
